$z[] = '<td rowspan="10">Address Book Entries</td>';
$z[] = '<td>Regular Length</td>';
$z[] = '	<input %s  name="dev_init_00" value=%s type="radio">';
$z[] = '<td>Maximum Length</td>';
$z[] = '	<input %s  name="dev_init_01" value=%s type="radio">';
$z[] = '<td>Special Character</td>';
$z[] = '	<input %s  name="dev_init_02" value=%s type="radio">';
$z[] = '<td>Blank Name</td>';
$z[] = '	<input %s  name="dev_init_03" value=%s type="radio">';
$z[] = '<td>Regular Length, email</td>';
$z[] = '	<input %s  name="dev_init_04" value=%s type="radio">';
$z[] = '<td>Regular Length, graphic</td>';
$z[] = '	<input %s  name="dev_init_05" value=%s type="radio">';
$z[] = '<td>Regular Length, Address</td>';
$z[] = '	<input %s  name="dev_init_06" value=%s type="radio">';
$z[] = '<td>Deleted Entry</td>';
$z[] = '	<input %s  name="dev_init_07" value=%s type="radio">';
$z[] = '<td>Non-Latin Entry</td>';
$z[] = '	<input %s  name="dev_init_08" value=%s type="radio">';
$z[] = '<td>Contact Groups</td>';
$z[] = '	<input %s  name="dev_init_09" value=%s type="radio">';
$z[] = '<td rowspan="5">PIM Data: Datebook/Calendar, Memos</td>';
$z[] = '<td>Regular Length</td>';
$z[] = '	<input %s  name="dev_init_10" value=%s type="radio">';
$z[] = '<td>Maximum Length</td>';
$z[] = '	<input %s  name="dev_init_11" value=%s type="radio">';
$z[] = '<td>Deleted Entry</td>';
$z[] = '	<input %s  name="dev_init_12" value=%s type="radio">';
$z[] = '<td>Special Character</td>';
$z[] = '	<input %s  name="dev_init_13" value=%s type="radio">';
$z[] = '<td>Blank Entry</td>';
$z[] = '	<input %s  name="dev_init_14" value=%s type="radio">';
$z[] = '<td rowspan="6">Call Logs</td>';
$z[] = '<td>Incoming</td>';
$z[] = '	<input %s  name="dev_init_15" value=%s type="radio">';
$z[] = '<td>Outgoing</td>';
$z[] = '	<input %s  name="dev_init_16" value=%s type="radio">';
$z[] = '<td>Missed</td>';
$z[] = '	<input %s  name="dev_init_17" value=%s type="radio">';
$z[] = '<td>Incoming – Deleted</td>';
$z[] = '	<input %s  name="dev_init_18" value=%s type="radio">';
$z[] = '<td>Outgoing – Deleted</td>';
$z[] = '	<input %s  name="dev_init_19" value=%s type="radio">';
$z[] = '<td>Missed   - Deleted</td>';
$z[] = '	<input %s  name="dev_init_20" value=%s type="radio">';
$z[] = '<td rowspan="11">Text Messages</td>';
$z[] = '<td>Incoming SMS – Read</td>';
$z[] = '	<input %s  name="dev_init_21" value=%s type="radio">';
$z[] = '<td>Incoming SMS – Unread</td>';
$z[] = '	<input %s  name="dev_init_22" value=%s type="radio">';
$z[] = '<td>Outgoing SMS</td>';
$z[] = '	<input %s  name="dev_init_23" value=%s type="radio">';
$z[] = '<td>Incoming EMS – Read</td>';
$z[] = '	<input %s  name="dev_init_24" value=%s type="radio">';
$z[] = '<td>Incoming EMS – Unread</td>';
$z[] = '	<input %s  name="dev_init_25" value=%s type="radio">';
$z[] = '<td>Outgoing EMS</td>';
$z[] = '	<input %s  name="dev_init_26" value=%s type="radio">';
$z[] = '<td>Incoming SMS – Deleted</td>';
$z[] = '	<input %s  name="dev_init_27" value=%s type="radio">';
$z[] = '<td>Outgoing SMS – Deleted</td>';
$z[] = '	<input %s  name="dev_init_28" value=%s type="radio">';
$z[] = '<td>Incoming EMS – Deleted</td>';
$z[] = '	<input %s  name="dev_init_29" value=%s type="radio">';
$z[] = '<td>Outgoing EMS – Deleted</td>';
$z[] = '	<input %s  name="dev_init_30" value=%s type="radio">';
$z[] = '<td>Non-Latin SMS/EMS</td>';
$z[] = '	<input %s  name="dev_init_31" value=%s type="radio">';
$z[] = '<td rowspan="6">MMS Messages</td>';
$z[] = '<td>Incoming Audio</td>';
$z[] = '	<input %s  name="dev_init_32" value=%s type="radio">';
$z[] = '<td>Incoming Graphic</td>';
$z[] = '	<input %s  name="dev_init_33" value=%s type="radio">';
$z[] = '<td>Incoming Video</td>';
$z[] = '	<input %s  name="dev_init_34" value=%s type="radio">';
$z[] = '<td>Outgoing Audio</td>';
$z[] = '	<input %s  name="dev_init_35" value=%s type="radio">';
$z[] = '<td>Outgoing Graphic</td>';
$z[] = '	<input %s  name="dev_init_36" value=%s type="radio">';
$z[] = '<td>Outgoing Video</td>';
$z[] = '	<input %s  name="dev_init_37" value=%s type="radio">';
$z[] = '<td rowspan="1">Application Data</td>';
$z[] = '<td>Device Specific App Data</td>';
$z[] = '	<input %s  name="dev_init_38" value=%s type="radio">';
$z[] = '<td rowspan="6">Stand-alone data files</td>';
$z[] = '<td>Audio</td>';
$z[] = '	<input %s  name="dev_init_39" value=%s type="radio">';
$z[] = '<td>Graphic</td>';
$z[] = '	<input %s  name="dev_init_40" value=%s type="radio">';
$z[] = '<td>Video</td>';
$z[] = '	<input %s  name="dev_init_41" value=%s type="radio">';
$z[] = '<td>Audio – Deleted</td>';
$z[] = '	<input %s  name="dev_init_42" value=%s type="radio">';
$z[] = '<td>Graphic - Deleted</td>';
$z[] = '	<input %s  name="dev_init_43" value=%s type="radio">';
$z[] = '<td>Video - Deleted</td>';
$z[] = '	<input %s  name="dev_init_44" value=%s type="radio">';
$z[] = '<td rowspan="3">Internet Data</td>';
$z[] = '<td>Visited Sites</td>';
$z[] = '	<input %s  name="dev_init_45" value=%s type="radio">';
$z[] = '<td>Bookmarks</td>';
$z[] = '	<input %s  name="dev_init_46" value=%s type="radio">';
$z[] = '<td>E-mail</td>';
$z[] = '	<input %s  name="dev_init_47" value=%s type="radio">';
$z[] = '<td rowspan="2">Location Data</td>';
$z[] = '<td>GPS Coordinates</td>';
$z[] = '	<input %s  name="dev_init_48" value=%s type="radio">';
$z[] = '<td>Geo-tagged Data</td>';
$z[] = '	<input %s  name="dev_init_49" value=%s type="radio">';
$z[] = '<td rowspan="4">Social Media Data</td>';
$z[] = '<td>Facebook</td>';
$z[] = '	<input %s  name="dev_init_50" value=%s type="radio">';
$z[] = '<td>Twitter</td>';
$z[] = '	<input %s  name="dev_init_51" value=%s type="radio">';
$z[] = '<td>LinkedIn</td>';
$z[] = '	<input %s  name="dev_init_52" value=%s type="radio">';
$z[] = '<td>Instagram</td>';
$z[] = '	<input %s  name="dev_init_53" value=%s type="radio">';
$zz[] = '<td rowspan="5">Abbreviated Dialing Numbers (ADN)</td>';
$zz[] = '<td>Maximum Length</td>';
$zz[] = '	<input %s  name="sim_init_00" value=%s type="radio">';
$zz[] = '<td>Special Character</td>';
$zz[] = '	<input %s  name="sim_init_01" value=%s type="radio">';
$zz[] = '<td>Blank Name</td>';
$zz[] = '	<input %s  name="sim_init_02" value=%s type="radio">';
$zz[] = '<td>Non-ASCII Entry</td>';
$zz[] = '	<input %s  name="sim_init_03" value=%s type="radio">';
$zz[] = '<td>Regular Length - Deleted Number</td>';
$zz[] = '	<input %s  name="sim_init_04" value=%s type="radio">';
$zz[] = '<td rowspan="1">Call Logs</td>';
$zz[] = '<td>Last Numbers Dialed (LND)</td>';
$zz[] = '	<input %s  name="sim_init_05" value=%s type="radio">';
$zz[] = '<td rowspan="6">Text Messages</td>';
$zz[] = '<td>Incoming SMS - Read</td>';
$zz[] = '	<input %s  name="sim_init_06" value=%s type="radio">';
$zz[] = '<td>Incoming SMS - Unread</td>';
$zz[] = '	<input %s  name="sim_init_07" value=%s type="radio">';
$zz[] = '<td>Non-ASCII SMS</td>';
$zz[] = '	<input %s  name="sim_init_08" value=%s type="radio">';
$zz[] = '<td>Incoming SMS - Deleted</td>';
$zz[] = '	<input %s  name="sim_init_09" value=%s type="radio">';
$zz[] = '<td>Non-ASCII EMS</td>';
$zz[] = '	<input %s  name="sim_init_10" value=%s type="radio">';
$zz[] = '<td>Incoming EMS - Deleted</td>';
$zz[] = '	<input %s  name="sim_init_11" value=%s type="radio">';
